/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.jlleitschuh.disclosure.automated.app

import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.parameters.options.required
import org.jlleitschuh.disclosure.automated.driver.selenium.GitHubSecurityAdvisoriesSeleniumDriver
import com.github.ajalt.clikt.parameters.options.option

class AutomatedDisclosure : CliktCommand() {
    private val username: String by option(help = "GitHub Username", envvar = "GIT_HUB_USERNAME").required()
    private val password: String by option(help = "GitHub Password", envvar = "GIT_HUB_PASSWORD").required()
    private val twoFactorSecret: String by option(
        help = "GitHub Two Factor Secret. This is not a one-time secret. This is the secret seed value for the OTP generator.",
        envvar = "GIT_HUB_TWO_FACTOR_CODE"
    ).required()

    override fun run() {
        GitHubSecurityAdvisoriesSeleniumDriver.create().use {
            it.login(username, password, twoFactorSecret)
        }
    }
}

fun main(argv: Array<out String>) {
    AutomatedDisclosure().main(argv)
}
