/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.jlleitschuh.disclosure.automated.app

import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.parameters.options.option
import org.jlleitschuh.disclosure.automated.driver.selenium.GitHubSecurityAdvisoriesSeleniumDriver

class AutomatedDisclosure : CliktCommand() {
    // val username by option(envvar = "GIT_HUB_USERNAME")
    // val password by option(envvar = "GIT_HUB_PASSWORD")

    override fun run() {
        GitHubSecurityAdvisoriesSeleniumDriver.create().use {
            it.login()
        }
    }
}

fun main(argv: Array<out String>) {
    AutomatedDisclosure().main(argv)
}
