/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    // Apply the common convention plugin for shared build configuration between library and application projects.
    id("org.jlleitschuh.disclosure.automated.kotlin-common-conventions")

    // Apply the java-library plugin for API and implementation separation.
    `java-library`
}

dependencies {
    constraints {
        implementation("org.fluentlenium:fluentlenium-core:4.6.1")
        implementation("com.j256.two-factor-auth:two-factor-auth:1.3")
    }
}
